### PR TITLE
new feature

### PR DESCRIPTION
**Pull request by queenieukpong**
bank transaction new feature

### CODE REVIEW

**Comment by joshuaunity** [comment]
Wowwww, you are the only person so far that got the getTransaction feature correctly. WELDONE!!!

**Comment by joshuaunity** [comment]
You didn't particularly get the daily withdrawal limit feature, although you where on the right path but didn't really hit the hammer on the nail.

**Comment by queenieukpong** [comment]
So what do i need to do now? do i send another pull request @joshuaunity

**Comment by queenieukpong** [comment]
so what can i do now? do i need to send another pull request? @joshuaunity

**Comment by joshuaunity** [comment]
> so what can i do now? do i need to send another pull request? @joshuaunity

No leave this one and close the other one

**Comment by joshuaunity** [comment]
I have acknowledged your 3rd assignment, and look forward to your 4th assignment, so far you are one of my most zealous students and I expect better things form you in the future.

**Pull request merged**
